/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.scale;

import model.BareOrder;
import model.OrderDiagnostic;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

import java.util.Properties;

public class TestApp {
    public static void main(String[] args) throws Exception {
        System.out.println("HIHI");
    }
}
