/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.scale;

import org.junit.Test;
import static org.junit.Assert.*;

public class TopologyAppTest {
    @Test public void testAppHasAGreeting() {
        TopologyApp classUnderTest = new TopologyApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
